name: Context Demo

on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    job1:
        name: Erste Analyse
        runs-on: ubuntu-latest
        env:
            geheim: ${{ secrets.MY_SECRET }}
        steps:
            - name: Zeige unser Geheimnis
              run: echo $geheim

            - name: Secret auf Datev pr端fen
              if: env.geheim == 'I love Datev'
              run: echo "Viel liebe f端r Datev"

            - name: Secret auf Datev production pr端fen
              if: env.geheim == 'I love really Datev'
              run: echo "Viel liebe f端r Datev (Production Version)"

            - name: Zeige GitHub Kontext
              run: echo '${{ toJson(github) }}'

            - name: Zeige Steps Kontext
              run: echo '${{ toJson(steps) }}'

            - name: Zeige Runner Kontext
              run: echo '${{ toJson(runner) }}'